//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { SlidingDateRangeBag } from "@Obsidian/ViewModels/Controls/slidingDateRangeBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/** A bag that contains filters information for the connection request board. */
export type ConnectionRequestBoardFiltersBag = {
    /** Gets or sets the available connection states that can be used to filter connection requests. */
    availableConnectionStates?: ListItemBag[] | null;

    /** Gets or sets the available "last activity" types that can be used to filter connection requests. */
    availableLastActivityTypes?: ListItemBag[] | null;

    /** Gets or sets the available connection statuses that can be used to filter connection requests. */
    availableStatuses?: ListItemBag[] | null;

    /** Gets or sets the campus identifier to be used to filter various aspects of the connection request board. */
    campusId?: number | null;

    /** Gets or sets the person alias identifier of the "connector" to be used to filter connection requests. */
    connectorPersonAliasId?: number | null;

    /** Gets or sets the date range to be used to filter connection requests (using the last activity date). */
    dateRange?: SlidingDateRangeBag | null;

    /** Gets or sets whether to only include connection requests that are "due today or already past due". */
    pastDueOnly?: boolean | null;

    /** Gets or sets the person alias identifier of the "requester" to be used to filter connection requests. */
    requesterPersonAliasId?: number | null;

    /** Gets or sets the selected connection states to be used to filter connection requests. */
    selectedConnectionStates?: string[] | null;

    /** Gets or sets the selected "last activity" types to be used to filter connection requests. */
    selectedLastActivityTypes?: string[] | null;

    /** Gets or sets the selected connection statuses to be used to filter connection requests. */
    selectedStatuses?: string[] | null;

    /** Gets or sets the model property to be used for sorting connection requests. */
    sortProperty: number;
};
