//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";

/** A bag that contains information about a location for an additional time sign-up for the group schedule toolbox. */
export type AdditionalTimeSignUpLocationBag = {
    /** Gets or sets the unique identifier. */
    guid?: Guid | null;

    /** Gets or sets whether the maximum number of people have already been scheduled. */
    isAtCapacity: boolean;

    /** Gets or sets the maximum capacity. */
    maximumCapacity?: number | null;

    /** Gets or sets the name. */
    name?: string | null;

    /** Gets or sets the order. */
    order: number;

    /** Gets or sets the count of people needed at this location. */
    peopleNeededCount: number;

    /** Gets or sets the count of people already scheduled at this location. */
    peopleScheduledCount: number;
};
