//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";
import { AdditionalTimeSignUpBag } from "@Obsidian/ViewModels/Blocks/Group/Scheduling/GroupScheduleToolbox/additionalTimeSignUpBag";

/** A bag that contains information about additional time sign-ups for the group schedule toolbox. */
export type AdditionalTimeSignUpsBag = {
    /** Gets or sets the unique identifier of the group to which these additional time sign-ups belong. */
    groupGuid?: Guid | null;

    /** Gets or sets the immediate additional time sign-ups, grouped by date. */
    immediateSignUpsByDate?: Record<string, AdditionalTimeSignUpBag[]> | null;

    /** Gets or sets the instructions HTML. */
    instructionsHtml?: string | null;

    /** Gets or sets the non-immediate additional time sign-ups, grouped by date. */
    nonImmediateSignUpsByDate?: Record<string, AdditionalTimeSignUpBag[]> | null;
};
